#!/usr/bin/env python3
"""
Train the FlyOnTime XGBoost regressor.

This script is the clean Python version of the XGBoost regressor notebook.
It keeps the notebook modeling logic, but changes only the loading step:

the regressor reads the local parquet generated by the classifier script:
    data/df_train_final.parquet

This matches the notebook workflow where the classifier preprocessing creates
`df_train_final`, then saves it as parquet so the regressor can reuse the same
cleaned / feature-engineered dataset.

Run order:
    1. python train_xgboost_classifier.py
    2. python train_xgboost_regressor.py

Example:
    python train_xgboost_regressor.py \
        --data-path data/df_train_final.parquet \
        --tracking-uri https://ppml2026-ppml-mlflow.hf.space
"""

from __future__ import annotations

import argparse
import json
import os
import warnings
from pathlib import Path
from typing import Any

import joblib
import mlflow
import mlflow.xgboost
import numpy as np
import pandas as pd
from pandas.api.types import is_datetime64_any_dtype
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import KFold, RandomizedSearchCV, train_test_split
from sklearn.preprocessing import OrdinalEncoder
from xgboost import XGBRegressor

warnings.filterwarnings("ignore")

DEFAULT_DATA_PATH = "data/df_train_final.parquet"
DEFAULT_DATETIME_COLS = ["flight_date", "scheduled_departure_dep", "scheduled_arrival_arr"]
COLS_A_VIRER = ["departure_delay_min", "arrival_delay_min", "time_dep", "time_arr"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train FlyOnTime XGBoost regressor from local df_train_final parquet")

    parser.add_argument("--data-path", default=os.getenv("DF_TRAIN_FINAL_PATH", DEFAULT_DATA_PATH))

    parser.add_argument("--tracking-uri", default=os.getenv("MLFLOW_TRACKING_URI", "https://ppml2026-ppml-mlflow.hf.space"))
    parser.add_argument("--experiment-name", default=os.getenv("MLFLOW_EXPERIMENT_NAME", "FlyOnTime_regressor"))
    parser.add_argument("--run-name", default=os.getenv("MLFLOW_RUN_NAME", "XGBoost_Regressor"))
    parser.add_argument("--registered-name", default=os.getenv("MLFLOW_REGISTERED_NAME", "XGBoost_Regressor_registered"))
    parser.add_argument("--alias", default=os.getenv("MLFLOW_MODEL_ALIAS", "challenger"))
    parser.add_argument("--developer", default=os.getenv("MODEL_DEVELOPER", "Ludo"))

    parser.add_argument("--test-size", type=float, default=0.2)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument("--n-iter", type=int, default=20)
    parser.add_argument("--cv-splits", type=int, default=5)
    parser.add_argument("--artifacts-dir", default="artifacts_regressor")
    return parser.parse_args()


def load_df_train_final(data_path: str) -> tuple[pd.DataFrame, str]:
    path = Path(data_path)

    if not path.exists():
        raise FileNotFoundError(
            f"df_train_final parquet not found: {path}. "
            "Run train_xgboost_classifier.py first, or pass --data-path to the correct parquet."
        )

    if path.suffix.lower() != ".parquet":
        raise ValueError("The regressor expects a local .parquet file generated by the classifier script.")

    df = pd.read_parquet(path)

    if df.empty:
        raise ValueError(f"df_train_final parquet is empty: {path}")

    print(f"df_train_final loaded locally: {path}")
    print(f"Shape: {df.shape}")
    return df, str(path)


def datetime_clean(df: pd.DataFrame, datetime_cols: list[str] | None = None) -> pd.DataFrame:
    datetime_cols = datetime_cols or DEFAULT_DATETIME_COLS
    df = df.copy()
    bad_datetime_cols: list[str] = []

    for col in datetime_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")
            if not is_datetime64_any_dtype(df[col]):
                bad_datetime_cols.append(col)

    usable_datetime_cols = [col for col in datetime_cols if col in df.columns and col not in bad_datetime_cols]

    if "flight_date" in usable_datetime_cols:
        df["flight_month"] = df["flight_date"].dt.month
        df["flight_day"] = df["flight_date"].dt.day
        df["flight_dayofweek"] = df["flight_date"].dt.dayofweek

    if "scheduled_departure_dep" in usable_datetime_cols:
        df["sched_dep_hour"] = df["scheduled_departure_dep"].dt.hour
        df["sched_dep_minute"] = df["scheduled_departure_dep"].dt.minute

    if "scheduled_arrival_arr" in usable_datetime_cols:
        df["sched_arr_hour"] = df["scheduled_arrival_arr"].dt.hour
        df["sched_arr_minute"] = df["scheduled_arrival_arr"].dt.minute

    print("Colonnes datetime problématiques droppées :", bad_datetime_cols)
    return df.drop(columns=datetime_cols, errors="ignore")


def prepare_xy(df_train_final: pd.DataFrame) -> tuple[pd.DataFrame, pd.Series]:
    if "arrival_delay_min" not in df_train_final.columns:
        raise KeyError("Column `arrival_delay_min` is required as the regression target.")

    df_train_final = df_train_final[df_train_final["arrival_delay_min"].notnull()].copy()

    y = df_train_final["arrival_delay_min"].astype(float)
    X = df_train_final.drop(
        columns=COLS_A_VIRER + ["arrival_delay_min", "retard_arrivee"],
        errors="ignore",
    ).copy()

    X = datetime_clean(X, DEFAULT_DATETIME_COLS)
    return X, y


def fit_preprocess_train_test(X_train: pd.DataFrame, X_test: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    X_train = X_train.copy()
    X_test = X_test.copy()

    cat_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
    encoder = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)

    if cat_cols:
        X_train[cat_cols] = encoder.fit_transform(X_train[cat_cols].astype(str))
        X_test[cat_cols] = encoder.transform(X_test[cat_cols].astype(str))

    num_cols = X_train.select_dtypes(include=np.number).columns.tolist()
    medians = X_train[num_cols].median()
    X_train[num_cols] = X_train[num_cols].fillna(medians)
    X_test[num_cols] = X_test[num_cols].fillna(medians)

    X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

    preprocessing = {
        "cat_cols": cat_cols,
        "num_cols": num_cols,
        "feature_columns": X_train.columns.tolist(),
        "encoder": encoder,
        "medians": medians,
    }
    return X_train, X_test, preprocessing


def save_preprocessing_artifacts(preprocessing: dict[str, Any], artifacts_dir: str, data_path: str) -> Path:
    path = Path(artifacts_dir)
    path.mkdir(parents=True, exist_ok=True)

    joblib.dump(preprocessing["encoder"], path / "ordinal_encoder.joblib")
    preprocessing["medians"].to_json(path / "train_medians.json", indent=2)

    metadata = {
        "cat_cols": preprocessing["cat_cols"],
        "num_cols": preprocessing["num_cols"],
        "feature_columns": preprocessing["feature_columns"],
        "datetime_cols": DEFAULT_DATETIME_COLS,
        "drop_cols": COLS_A_VIRER,
        "target": "arrival_delay_min",
        "source_local_parquet": data_path,
    }
    with open(path / "preprocessing_metadata.json", "w", encoding="utf-8") as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)

    return path


def log_xgboost_model(best_model: XGBRegressor, model_name: str, registered_name: str, input_example: pd.DataFrame):
    try:
        return mlflow.xgboost.log_model(
            xgb_model=best_model,
            name=model_name,
            registered_model_name=registered_name,
            input_example=input_example,
            model_format="json",
        )
    except TypeError:
        return mlflow.xgboost.log_model(
            xgb_model=best_model,
            artifact_path=model_name,
            registered_model_name=registered_name,
            input_example=input_example,
            model_format="json",
        )


def set_alias_if_possible(registered_name: str, alias: str, model_info: Any) -> None:
    version = getattr(model_info, "registered_model_version", None)
    if version is None:
        print("Model alias not set: registered model version unavailable from MLflow response.")
        return
    client = mlflow.tracking.MlflowClient()
    client.set_registered_model_alias(registered_name, alias, str(version))


def main() -> None:
    args = parse_args()

    mlflow.set_tracking_uri(args.tracking_uri)
    mlflow.set_experiment(args.experiment_name)
    while mlflow.active_run():
        mlflow.end_run()

    df_train_final, resolved_data_path = load_df_train_final(args.data_path)
    X, y = prepare_xy(df_train_final)

    X_train_raw, X_test_raw, y_train, y_test = train_test_split(
        X,
        y,
        test_size=args.test_size,
        random_state=args.random_state,
    )

    X_train, X_test, preprocessing = fit_preprocess_train_test(X_train_raw, X_test_raw)
    artifacts_path = save_preprocessing_artifacts(preprocessing, args.artifacts_dir, resolved_data_path)

    cv = KFold(n_splits=args.cv_splits, shuffle=True, random_state=args.random_state)
    param_dist = {
        "n_estimators": [200, 300, 500, 700],
        "learning_rate": [0.01, 0.03, 0.05, 0.1],
        "max_depth": [3, 4, 5, 6, 8],
        "min_child_weight": [1, 3, 5, 7],
        "subsample": [0.6, 0.8, 1.0],
        "colsample_bytree": [0.6, 0.8, 1.0],
        "gamma": [0, 0.1, 0.3, 0.5],
        "reg_alpha": [0, 0.01, 0.1, 1],
        "reg_lambda": [1, 1.5, 2, 3],
    }

    base_model = XGBRegressor(objective="reg:squarederror", random_state=args.random_state, n_jobs=-1)
    random_search = RandomizedSearchCV(
        estimator=base_model,
        param_distributions=param_dist,
        n_iter=args.n_iter,
        scoring="neg_mean_absolute_error",
        cv=cv,
        verbose=2,
        random_state=args.random_state,
        n_jobs=-1,
        refit=True,
    )

    model_name = f"{args.run_name}_{args.developer}"

    with mlflow.start_run(run_name=args.run_name):
        mlflow.set_tag("developer", args.developer)
        mlflow.set_tag("model_full_name", model_name)
        mlflow.set_tag("target", "arrival_delay_min")
        mlflow.set_tag("model_type", "regression")
        mlflow.set_tag("optimization_metric", "neg_mean_absolute_error")
        mlflow.log_param("source_local_parquet", resolved_data_path)
        mlflow.log_param("n_features", X_train.shape[1])
        mlflow.log_param("n_train_rows", X_train.shape[0])
        mlflow.log_param("n_test_rows", X_test.shape[0])

        print("Searching best XGBoost regressor hyperparameters...")
        random_search.fit(X_train, y_train)
        best_model = random_search.best_estimator_

        y_pred_train = best_model.predict(X_train)
        y_pred_test = best_model.predict(X_test)

        metrics = {
            "train_mae": mean_absolute_error(y_train, y_pred_train),
            "train_rmse": np.sqrt(mean_squared_error(y_train, y_pred_train)),
            "train_r2": r2_score(y_train, y_pred_train),
            "test_mae": mean_absolute_error(y_test, y_pred_test),
            "test_rmse": np.sqrt(mean_squared_error(y_test, y_pred_test)),
            "test_r2": r2_score(y_test, y_pred_test),
        }

        mlflow.log_params(random_search.best_params_)
        mlflow.log_metric("best_cv_score_neg_mae", float(random_search.best_score_))
        mlflow.log_metrics({k: float(v) for k, v in metrics.items()})
        mlflow.log_artifacts(str(artifacts_path), artifact_path="preprocessing")

        model_info = log_xgboost_model(best_model, model_name, args.registered_name, X_test.head(5))
        set_alias_if_possible(args.registered_name, args.alias, model_info)

        print("\n===== BEST PARAMS =====")
        print(random_search.best_params_)
        print("\n===== FINAL METRICS =====")
        for key, value in metrics.items():
            print(f"{key}: {value:.4f}")
        print(f"\nModel registered: {args.registered_name} @{args.alias}")


if __name__ == "__main__":
    main()
